config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    #path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    #path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("stockbuddy.users.urls", namespace="users")),
    #path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('', include(('stockbuddy.urls', 'stockbuddy'), namespace='stockbuddy')),
    #url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    #url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

stockbuddy/urls.py
from django.conf import settings
from django.urls import include, path
from . import views
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.stock_view, name='home'),
    path('stock/<str:symbol>', views.stockdetail_view, name='detailed'),
]

stockbuddy/users/urls.py
from django.urls import path

from stockbuddy.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

stockbuddy/models.py
from django.db import models
# Create your models here.
import pandas as pd
import numpy as np
import yfinance as yf
from statsmodels.tsa.statespace.sarimax import SARIMAX
from django.contrib.postgres.fields import ArrayField
import requests
from statsmodels.tsa.arima_model import ARIMA

headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'}

def Arima(symbol):
	infy = yf.Ticker("%s.NS" % symbol)
	dataset = infy.history(period="5y")
	dataset.index = range(len(dataset))
	model = ARIMA(dataset['Close'], order=(20,1,3))
	model_fit = model.fit()
	x=model_fit.forecast(3)
	y=list(x[0])
	mlprediction = [round(num, 2) for num in y]
	return mlprediction


def Report(symbol):
	r=requests.get('https://www.nseindia.com/api/annual-reports?index=equities&symbol=%s' % symbol, headers=headers)
	listreport=[]
	for i in range(2):
		listreport.append(r.json().get('data')[i].get('fileName'))
		listreport.append(r.json().get('data')[i].get('toYr'))
	return listreport

class StockData(models.Model):
	symbol = models.CharField(max_length=12,default=None,primary_key=True)
	mlprediction = ArrayField(models.DecimalField(blank=True,null=True,max_digits=7, decimal_places=2),blank=True,null=True)
	listreport=ArrayField(models.TextField(blank=True,null=True),blank=True,null=True)

	def __str__(self):
		return self.symbol

	def __unicode__(self):
		return self.symbol

	def save(self, *args, **kwargs) -> None:
		self.mlprediction=Arima(self.symbol)
		self.listreport=Report(self.symbol)
		super().save(*args, **kwargs)

stockbuddy/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

stockbuddy/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

stockbuddy/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

stockbuddy/views.py
from django.http import HttpResponse
import requests
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
import feedparser
from .models import StockData
from django.forms.models import model_to_dict
from flair.models import TextClassifier
from flair.data import Sentence

# TODO: requirements file
# TODO: remove all comments you made
# TODO: remove junk files
# TODO: login logic

headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'}

def stock_view(request):
	import yfinance as yf
	dictstock={}
	dictnews={}
	query=StockData.objects.all()

	for obj in query:
		stockdata = yf.Ticker("%s.NS" % obj.symbol)
		name=stockdata.info['longName']
		hist = stockdata.history(period="1d")
		ltp=hist.iloc[-1].Close
		dictstock[obj.symbol]=(name,ltp)

	rss_url='https://news.google.com/rss/search?q=Indian%20Stock%20Market&hl=en-IN&gl=IN&ceid=IN:en&hl=en-IN'
	news_feed = feedparser.parse(rss_url)
	for i in range(4):
		dictnews[news_feed.entries[i].title]=news_feed.entries[i].link

	return render(request,"home.html",{"dictstock":dictstock,"dictnews":dictnews})

def newsprediction(title):
	classifier = TextClassifier.load('bestmodel.pt')
	sentence = Sentence(title)
	classifier.predict(sentence)
	n= str(sentence.labels[0]).split()[0]
	if n=="0":
		return 0
	else:
		return 1

def analysis(score,percentchange):
	if score==0:
		newsmark=5
	elif score==1:
		newsmark=3
	else:
		newsmark=0
	newsmark=newsmark*0.25

	if percentchange>=3:
		mlmark=5
	elif percentchange<=-3:
		mlmark=0
	else:
		mlmark=3
	percentchange=percentchange*0.75
	
	return newsmark+mlmark

def stockdetail_view(request,symbol):
	import yfinance as yf
	stockdata = yf.Ticker("%s.NS" % symbol)
	name=stockdata.info['longName']
	hist = stockdata.history(period="1mo")
	ltp=hist.iloc[-1].Close
	Graph=hist.iloc[-7:].Close.to_json().replace("\"", "")
	Obj=StockData.objects.get(symbol=symbol)
	reports=Obj.listreport
	score=0
	rss_url='https://news.google.com/rss/search?q=%s&hl=en-IN&gl=IN&ceid=IN:en&hl=en-IN' % name.replace(" ","%20")
	dictnews={}
	news_feed = feedparser.parse(rss_url)
	for i in range(2):
		newsscore=int(newsprediction(news_feed.entries[i].title.rsplit("-",1)[0]))
		dictnews[news_feed.entries[i].title]=(news_feed.entries[i].link,newsscore)
		score+=newsscore

	y=Obj.mlprediction
	mlquery=[float(i) for i in y]
	percentchange=((mlquery[2]-ltp)/ltp)*100
	analysisscore=analysis(score,percentchange)

	return render(request,"stockview.html",{"symbol":symbol,"name":name,"ltp":ltp,"Graph":Graph,"dictnews":dictnews,"mlquery":mlquery,"reports":reports,"analysisscore":analysisscore})

stockbuddy/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}StockBuddy{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'stockbuddy:home' %}">StockBuddy</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'stockbuddy:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

stockbuddy/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<title> STOCKBUDDY </title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="theme-color" content="#2C2627">
		<!--===============================================================================================-->
		<link rel="icon" type="image/png" href="{% static 'event/images/icons/favicon.ico' %}" />
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'event/vendor/bootstrap/css/bootstrap.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'event/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'event/vendor/animate/animate.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'event/vendor/select2/select2.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'event/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'res/css/util.css' %}">
		<!--===============================================================================================-->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet">
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
		<!-- <script src="{% static 'js/tablesorter.windgets.min.js' %}"></script> -->
		<link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129276229-1"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'res/css/main.css' %}">


	</head>

	<body>
		<!--	<header>
		<nav class="navbar navbar-expand-md navbar navbar-dark bg-dark navbar sticky-top">
			<div class="container-fluid">
				<span class="navbar-brand mb-0 h1" id="heading">SAMATVA COLLEGE UNION</span>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarResponsive">

							<ul class="navbar-nav ml-auto">
								<!--		<li class="nav-item active">
						 	 <a class="nav-link" href="#">Results</a>
								</li>
						</ul>
                </div>
			</div>
		</nav>
	</header>-->
	<div class="headernew">
		{% if user.is_authenticated %}
		<h6>Welcome, {{request.user.username}}<br><a href="{% url "logout" %}">Logout</a></h6>
		{% else %}
		<h6><a href="{% url "login" %}">Login</a>&nbsp;or&nbsp;<a href="{% url "signup" %}">Signup</a></h6>
		{% endif %}
	</div>

		<div class="event">


			<h1 class="Dheading display-5" id="event_list">STOCKBUDDY</h1>

			<div class="limiter">

				<div class="container-table100">
					<div class="wrap-table100">
						<div class="table100">



							<!--	<p id='sc_br_r' style="text-align:center;"></p>-->

							<br>
							<table id="sc_br">
								<thead>
									<tr class="table100-head">
										<th class="column2">Stock</th>
										<th class="column2">Last Trading Point</th>

								</thead>
								<tbody>
									{% for symbol,values in dictstock.items %}
									<tr>
										<td id='y' class="column2"><a href="{% url "stockbuddy:detailed" symbol=symbol %}">{{values.0}}</a></td>
										<td id='p' class="column2">{{values.1}}</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>

							<br>
							<center>
								<h1 class="newstitle Dheading display-5" id="event_list">LATEST STOCK NEWS</h1><br>

								<table id="sc_br">
									<tbody>
									{% for title, link in dictnews.items %}
										<tr>
											<td id='y' class="newstd column2">
												<a href="{{link}}"><h6>{{title}}</h6></a>
											</td>
										</tr>
									{% endfor %}
									</tbody>
								</table>

						</div>
					</div>
				</div>
				<div class="div2 container-table100">
					<div class="wrap-table100">
						<div class="table100">
							<div class="table100">
								<!--	<p id='sc_br_r' style="text-align:center;"></p>-->
								<br>
								<table id="sc_br">
									<thead>
										<tr class="table100-head">
											<th class="column2">Ad Space</th>

									</thead>
									<tbody>
										<tr id='adspace'>
											<td id='y' class="column2"></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>



		<!--<footer>
		<div class="bg-dark footer-bottom text-center">
			Made With <img src="{% static "./img/redheart.png"%}" style="height:25px;width:25px"> at GEC Palakkad <br> ./tech_team : <a href="https://github.com/rejuls/daksha18"><img src="{% static "./img/GitHub_Logo_White.png"%}"
					style="height:150;width:62px"></a>
		</div>
	</footer>-->
		<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>

</html>



<!--===============================================================================================-->
<script src="{% static 'event/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
<script src="{% static 'event/vendor/bootstrap/js/popper.js'%}"></script>
<script src="{% static 'event/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
<script src="{% static 'event/vendor/select2/select2.min.js'%}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/tablesorter.min.js' %}"></script>
<!--===============================================================================================-->
<!-- <script>
	$(function() {
		$("#sc_br").tablesorter({
			sortList: [
				[1, 1],
			]
		});
		var f = parseInt($('#sc_br tbody tr:first-child #p').text());
		var s = parseInt($('#sc_br tbody tr:nth-child(2) #p').text());
		var y = $('#sc_br tbody tr:first-child #y').text();
		var d = f - s;
		$('#sc_br_r').text(y + " leads by " + d + " points");
	});
</script> -->



</body>

</html>